### PR TITLE
Fix install script issues first run

### LINKED ISSUE #660: [Other]: fresh clone won't clone DEV properly
### What is the issue?

Running `./install-afc.sh -b DEV` on a fresh clone won't actually install DEV until the 2nd try.

### PR DESCRIPTION
**Pull request by ejsears**
## Major Changes in this PR

Closes #660 

This pull request introduces several improvements and bug fixes to the update and installation scripts, focusing on better handling of git branches, improved update safety, and addressing a specific symlink issue that could cause repository problems. The main themes are improved git management, update reliability, and bug prevention.

**Git and update process improvements:**

* Added early parsing of the `-b` branch flag in `install-afc.sh` to ensure the script switches to the requested branch before sourcing include files, guaranteeing that the correct branch's logic is used during installation.
* Refactored the check for uncommitted changes into a reusable `check_for_uncommited_changes` function in `include/utils.sh`, and updated `clone_and_maybe_restart` to use this function, improving code clarity and maintainability. [[1]](diffhunk://#diff-9e64712e624ee22bf3a68f5ecd584c7f805f610eb1fb10ce184a3d3beb0b8352R52-R67) [[2]](diffhunk://#diff-9e64712e624ee22bf3a68f5ecd584c7f805f610eb1fb10ce184a3d3beb0b8352L66-R82)
* Updated the `exclude_from_klipper_git` function to only exclude `AFC*.py` files (instead of all `.py` files) from Klipper's git tracking, preventing accidental exclusion of unrelated files.

**Bug prevention and update reliability:**

* Added a `check_init_symlink` function to detect and repair a potential accidental symlink in `klippy/extras/__init__.py`, replacing it with the correct file from the Klipper source during updates to avoid dirty repo issues. This is now called during the update process. [[1]](diffhunk://#diff-91f04686173d0b0c6fe7b66c8e14e887f57ce6a144b68023c53d291a81e6fcc0R191-R206) [[2]](diffhunk://#diff-e640ec65703f5a9486beb53f428b150d6d1f3b3f7956b24766b783061f5d5ddeR32-R39)

## PR Checklist: (Checked-off items are either done or do not apply to this PR)
 
- [x] I have performed a self-review of my code
- [x] CHANGELOG.md is updated (if end-user facing)
- [ ] Documentation updated in AT-Documentation repository
- [x] Sent notification to software-design/software-discussions channel (as appropriate) requesting review
- [x] If this PR address a GitHub issue, the issue number is referenced in the PR description

**NOTE**: GitHub Copilot may be used for automated code reviews, however as it is an automated system, it's suggestions 
may not be correct. Please do not rely on it to catch all issues. Please review any suggestions it makes and use your 
own judgement to determine if they are correct.

### CODE REVIEW

File: include/check_commands.sh [hunk 1]
```diff
@@ -187,4 +187,24 @@ check_python_version() {
...
   echo "Python version $VERSION is OK."
   return 0
-}
\ No newline at end of file
+}
+
+# There was a small window of time when the klippy/extras/__init__.py might have been accidentally symlinked. This
+# function exists to check for it, and if it was, replace it with the proper __init__.py file from the Klipper source to
+# prevent issues with a dirty repo being present. This function is only called during an update, and only if a prior
+# installation is detected, so it should not cause any issues for users who have not been affected by this issue.
```
Comment (jimmyjon711) [inline include/check_commands.sh:195]: Would it be better to just try and do a `git checkout` of this file to restore this one from klipper git?

Comment (ejsears) [reply include/check_commands.sh:195]: I was thinking of that. But one of the reviews brought up a decent point if there by chance wasn't internet access, it would fail.

The `__init__.py` file itself hasn't changed in 9 years, so it is pretty static. Any having it in the code itself makes it pretty simple for anyone who may not be using a git installation

Comment (ejsears) [reply include/check_commands.sh:195]: I can do it as a backup maybe?

Comment (ejsears) [reply include/check_commands.sh:195]: Put it in as a backup, simple 1 line change.

**Review by jimmyjon711 — APPROVED** [review]
LGTM
